### ISSUE TITLE
fod not working

### ISSUE THREAD

**Issue by zainullahk** [ponces/treble_build_pe#10]
## Build date

```
Pixel Experience 12.0 v400.d
```

## Expected Behavior

```
fingerprint should be seen as on screen
```

## Current Behavior

```
it thinks the fingerprint sensor is on the back 

```

## Possible Solution

```
Edit here
```

## Steps to Reproduce

```
1.
2.
3.
4.
```

Device: 
GSI version: 
Vendor version:

**Comment by ponces** [comment]
Known issue. Next release should fix it.

**Comment by zainullahk** [comment]
also any fix for bluetooth? 
thats my main issue right now

**Comment by zainullahk** [comment]
thanks
