### ISSUE TITLE
mtp does not work

### ISSUE THREAD

**Issue by zainullahk** [ponces/treble_build_pe#12]
## Build date

```
Pixel Experience 12.0 v400.d 
```

## Expected Behavior

```
once windows makes a noise (meaning its connected) it should pop up and let me transfer data
```

## Current Behavior

```
i hear the noise but i cannot see the phone in file manager adb works 
```

## Possible Solution

```
Edit here
```

## Steps to Reproduce

```
1. plug in phone to pc
2. 
3.
4.
```

Device: Samsung Galaxy A71 
GSI version: 12
Vendor version: 11

**Comment by LegacyGamerHD** [comment]
thats a issue with samsungs custom kernel could fix it

**Comment by zainullahk** [comment]
yes but there is no custom kernel!

**Comment by ponces** [comment]
Known issue fixed with custom kernel as already advised.
Issue closed.
