### ISSUE TITLE
Always on display not working

### ISSUE THREAD

**Issue by zainullahk** [ponces/treble_build_pe#13]
## Build date

```
Pixel Experience 12.0 v400.d
```

## Expected Behavior

```
Always on display should work as expected
```

## Current Behavior

```
It does not work and there is no option in settings for it force always on display does fix it but it keeps the always on display always on 24/7 which drains battery like crazy
```

## Possible Solution

```
Edit here
```

## Steps to Reproduce

```
1.
2.
3.
4.
```

 i cannot get the logcat this error appears /system/bin/sh: can't create my_issue.log: Read-only file system

Device: Samsung Galaxy A71
GSI version: 12
Vendor version: 11

**Comment by ponces** [comment]
AOD is a feature enabled by device overlays and should only work reliably IF also present on stock rom.
Issue closed.
