### ISSUE TITLE
bluetooth is not working (yes i know this post is a duplicate nobody ever responds on phussons bug list

### ISSUE THREAD

**Issue by zainullahk** [ponces/treble_build_pe#14]
## Build date

```
Pixel Experience 12.0 v400.d
```

## Expected Behavior

```
when connecting any bluetooth device it should connect with no issue
```

## Current Behavior

```
it says connecting and then throws me  back to the main bluetooth menu when i click connect then shows me  the mac addres of the device and then dissapaears and then the name of the bluetooth device appears and it repeats this whole thing over and over
```

## Possible Solution

```
Edit here
```

## Steps to Reproduce

```
1.
2.
3.
4.
```

Device: Samsung galaxy A71
GSI version: 12
Vendor version: 11

**Comment by ponces** [comment]
Issue closed. Again.

**Comment by zainullahk** [comment]
> Issue closed. Again.
well if you ever want to check this issue here is the log 
[my_issue.log](https://github.com/ponces/treble_build_pe/files/7769552/my_issue.log)

**Comment by zainullahk** [comment]
i found a workaround 
enable force a2dp offload in phh treble settings

**Comment by ponces** [comment]
Great, as I [mentioned](https://github.com/ponces/treble_build_pe/issues/16#issuecomment-1000255063) on another issue of yours.

**Comment by ponces** [comment]
Please, use only one issue thread to report your issues.
From now on, only the one from the thread #16 will be considered.
Thanks

**Comment by zainullahk** [comment]
ok thanks!
