### ISSUE TITLE
sim 1 no audio

### ISSUE THREAD

**Issue by zainullahk** [ponces/treble_build_pe#15]
## Build date

```
Pixel Experience 12.0 v400.d
```

## Expected Behavior

```
Sim 1 should work properly
```

## Current Behavior

```
Incoming calls from sim 1 have no audio
```

## Possible Solution

```
Edit here
```

## Steps to Reproduce

```
1.
2.
3.
4.
```

Device: Samsung Galaxy A71
GSI version: 12
Vendor version: 11

**Comment by ponces** [comment]
Please, use the available issue template correctly. Issue closed.
