### ISSUE TITLE
TARGET module TurboAdapter requires non-existent TARGET module: libpowerstatshaldataprovider

### ISSUE THREAD

**Issue by LMFuture-Me** [ponces/treble_build_pe#3]
![image](https://user-images.githubusercontent.com/36117602/146664653-f9e5cde9-3ef4-4797-beed-7ac22de80397.png)

When I try to build on Debian. The following error occurred.

`============================================
device/phh/treble/base.mk:11: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
[100% 252/252] initializing build system ...
device/phh/treble/base.mk:11: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
[ 56% 438/776] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:57: warning: BOARD_PLAT_PUBLIC_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS instead.
system/sepolicy/Android.mk:62: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
system/sepolicy/Android.mk:64: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
system/sepolicy/Android.mk:148: warning: Be careful when using the SELINUX_IGNORE_NEVERALLOWS flag. It does not work in user builds and using it will not stop you from failing CTS.
[ 99% 775/776] finishing build rules ...
FAILED: 
build/make/core/main.mk:754: warning: Missing required dependencies:
TARGET module TurboAdapter requires non-existent TARGET module: libpowerstatshaldataprovider
build/make/core/main.mk:759: warning: Set BUILD_BROKEN_MISSING_REQUIRED_MODULES := true to bypass this check if this is intentional
build/make/core/main.mk:760: error: Build failed.
12:53:25 ckati failed with: exit status 1

!!! An error happened during script execution
!!! Please check console output for bad sync,
!!! failed patch application, etc.`

How to solve it. I am sure my system environment is very pure.

**Comment by thefiredragon** [comment]
You didn't setup your build environment well, I had under debian not this issue.

**Comment by ponces** [comment]
I assume you are building for an a64 target. This is an issue on PE gapps repo. As a workaround, you can follow the advice given at the end of the error message. Issue closed.
