### ISSUE TITLE
Bluetooth causes systemui to die

### ISSUE THREAD

**Issue by ItsLynix** [ponces/treble_build_pe#4]
Log:
[log.log](https://github.com/ponces/treble_build_pe/files/7741257/log.log)
 

## Build date
```
PixelExperience_arm64-ab-12.0-20211218-UNOFFICIAL
```

## Expected Behavior

```
A bluetooth device connects and is handled properly without issues
```

## Current Behavior

```
A bluetooth audio device connects, a media app attempts to make a media recommendation, systemui crashes
```

## Possible Solution

```
I'm unsure
```

## Steps to Reproduce

```
Disclaimer: This only started happening after a little while for me, and might not be fully reproducible
1. Pair a bluetooth device
2. Allow it to connect automatically
3. Ensure media recommendations is enabled
4. Watch systemui go black or freeze
```

device Samsung Galaxy A51
version twelve
vendor EUJ4 (Firmware Binary U5)

**Comment by ponces** [comment]
I saw on TG that you somehow fixed your issue by clearing BT cache. Is this true? Or did the issue return?

**Comment by ItsLynix** [comment]
> I saw on TG that you somehow fixed your issue by clearing BT cache. Is this true? Or did the issue return?

The issue has returned once more Yes

**Comment by ItsLynix** [comment]
After further testing, I've noticed that the issue appears to stop occurring once disabling media recommendations under Sound & Vibration > Media > Show media recommendations
