### ISSUE TITLE
Motorola one action Exynos 9609 JIO(volte) issue.

### ISSUE THREAD

**Issue by Suman-1410** [ponces/treble_build_pe#6]
## Build date

```
Example: PixelExperience_arm64-ab-12.0-20211218-UNOFFICIAL
```

## Expected Behavior

```
Edit here
```

## Current Behavior

```
Edit here
```

## Possible Solution

```
Edit here
```

## Steps to Reproduce

```
1.
2.
3.
4.
```

Device:  Motorola one Action 
GSI version:  android 12 latest 
Vendor version: 

"please fix the volte issue in exynos processor like 9609/9610 I can't use GSI for the problem As well as my phone dont have so much custom rom support. Please fix the issue"

**Comment by ponces** [comment]
There's no VoLTE for Samsung. Known "issue". Issue closed.

**Comment by ponces** [comment]
Isn't Shannon IMS (non-Samsung Exynos) available?

**Comment by ponces** [comment]
Duplicate issue on phhusson/treble_experimentations#2115 and phhusson/treble_experimentations#2116.
