### ISSUE TITLE
ringtone does not work when clicking volume buttons when there is a call 

### ISSUE THREAD

**Issue by zainullahk** [ponces/treble_build_pe#7]
device:samsung a71
Pixel Experience 12.0 v400.d
if i click the volume button while im recieving a call the ringtone just stops and the volume bar does not pop up

**Comment by ponces** [comment]
Clicking volume buttons during call ringing is the expected behavior on Android.
Next time, use the available issue template.
Issue closed.

**Comment by zainullahk** [comment]
thanks!
didnt know that cause its different on oneui
