### ISSUE TITLE
google photos unlimited missing 

### ISSUE THREAD

**Issue by zainullahk** [ponces/treble_build_pe#9]
## Build date

```
Pixel Experience 12.0 v400.d
```

## Expected Behavior

```
google photos should say high quality unlimited
```

## Current Behavior

```
It says storage is full (google photos is updated)
```

## Possible Solution

```
Most likely google thinks its a pixel 6 (because of the help app and pics of google apps in play store) g photos unlimited will work if the phone gets spoofed as a pixel 5 instead this can be done with magisk but cant be on non root
```

## Steps to Reproduce

```
1.
2.
3.
4.
```

Device: 
GSI version: 
Vendor version:

**Comment by ponces** [comment]
Google Photos unlimited storage workaround was dropped by PE as it is proved not be working anymore.
Check discussion [here](https://gerrit.pixelexperience.org/c/frameworks_base/+/14625) for more details.
Issue closed.
